# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3b8bd22b40cfd8f3b4a87b1a432c1b08"
name = "NanoGem Ring Builder"
handle = "nanogem-builder"
application_url = "https://dee-commit-performer-agents.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nanogem-solutions.myshopify.com"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "collections/create" ]
  uri = "/webhooks/collections/create"

  [[webhooks.subscriptions]]
  topics = [ "collections/update" ]
  uri = "/webhooks/collections/update"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_price_rules,read_product_listings,read_products,read_themes,unauthenticated_read_product_listings,write_products"

[auth]
redirect_urls = ["https://dee-commit-performer-agents.trycloudflare.com/auth/callback", "https://dee-commit-performer-agents.trycloudflare.com/auth/shopify/callback", "https://dee-commit-performer-agents.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://dee-commit-performer-agents.trycloudflare.com/api"
subpath = "nanogem-builder"
prefix = "apps"

[pos]
embedded = false
